### PR TITLE
Add CII Best Practices Badge to Dev

### PR DESCRIPTION
**Pull request by Nebrethar**
Describe your pull request here: 
This adds some work to the risk card.. finally!

I will continue working on it, including finishing integration of DoSOCSv2 to augur.

### CODE REVIEW

**Comment by Nebrethar** [comment]
image

**Comment by sgoggins** [comment]
@ccarterlandis : Thoughts on the build failure?

**Comment by ccarterlandis** [comment]
@sgoggins: The build failed because the alignment of the planets was off. You think I'm kidding, but I only wish I were...some tests are **very** finicky and sometimes, they just won't pass. Re-triggering the build usually makes it work (as it did this time), but we'll have to address this the inconsistency at another date.

**Comment by sgoggins** [comment]
Rodger that.  

Once again the physicists and astronomers prove useful.

Sean

**Pull request merged**
