### PR TITLE
Implemented clustering based methods and Isolation Forest for anomaly detection in the messages sample dataset from augur.

### PR DESCRIPTION
**Pull request by manangoel99**
This was done for #558 as a set of microtasks for GSoC 2020. This also fixes the error in my previous PR #592 which has since been closed. I've used KMeans clustering after Kernel PCA to find anomalies in the dataset after Doc2Vec. 
Similarly I have also used Isolation Forest to do the same job.

Signed-off-by: Manan Goel <manan.goel@research.iiit.ac.in>

### CODE REVIEW

**Comment by manangoel99** [comment]
I'm not sure why the tests are failing because I just added a notebook for anomaly detection. No other existing files were changed. Can someone guide me on as to how to go about fixing this.

**Comment by ccarterlandis** [comment]
Hey @manangoel99, glad to see you getting started with our microtasks! Please don't worry about the tests; we use encrypted credentials in our tests that are only available to trusted commits/PRs (meaning they are coming from inside this repository). We don't run tests on our notebooks so your changes won't break anything. That being said, I am working on a solution that I think will allow us to run the tests on all PRs, so hopefully I'll be able to roll that out soon! 

P.S. I've also assigned our resident machine learning guru @gabe-heim to your PR, as he is far more qualified to give you feedback than I am 😄

**Comment by manangoel99** [comment]
@gabe-heim Hi, There was some error while saving the notebook. I checked out the last checkpoint from the .ipynb-checkpoints directory and it was up to date with the last changes I made. It is working now.

**Comment by gabe-heim** [comment]
Hi @manangoel99 , thank you so much for your patience. I love the work you've done in your notebook! I would love to see more research-oriented work like this in notebooks, or if you want to try to integrate this work in Augur, you could try to implement a new `message_insights` model in our insight worker, and read my comment on #609 as a reference for how our worker architecture functions. I will also be sure to be readily available for any further questions/comments you have!

**Comment by manangoel99** [comment]
@gabe-heim Sorry for the delay in response. I'll start implementing the ```message_insights``` model in the insight worker so that I can get figure out how the worker functions. I will go through your comment in #609 and will let you know if I have any questions.

**Comment by manangoel99** [comment]
@gabe-heim @ccarterlandis I'm not sure if this is the right place to ask these doubts but in order to see how the insight worker functions, I set up augur but any requests to the insights worker, lead to the following error in the backend

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/manan/GSoC/CHAOSS/augur/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/manan/GSoC/CHAOSS/augur/augur/server.py", line 308, in transform
    data = func(*args, **kwargs)
  File "/home/manan/GSoC/CHAOSS/augur/augur/metrics/insight/insight.py", line 30, in top_insights
    results = pd.read_sql(topInsightsSQL, self.database, params={'repo_group_id': repo_group_id, 'num_repos': num_repos})
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/pandas/io/sql.py", line 438, in read_sql
    chunksize=chunksize,
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/pandas/io/sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/pandas/io/sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2191, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/manan/.virtualenvs/augur/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "repo_insights" does not exist
LINE 4:         FROM repo_insights JOIN repo ON repo.repo_id = repo_...

```

This is as the stack trace says that the relation does not exist in the database. What is the way around this?

**Comment by ccarterlandis** [comment]
Hi @manangoel99, sorry it took us a while to get back to you, especially when you've been having issues. Let's see if we can get this figured out.

Normally, the `make install` process will install the schema if you ask it to. That `repo_insights` table is part of that process, so if that table doesn't exist, something makes me think the schema installation process went awry. Can you provide the output of the following PostgreSQL query (run against the database having this issue):

```
SELECT
    table_schema || '.' || table_name
FROM
    information_schema.tables
WHERE
    table_type = 'BASE TABLE'
AND
    table_schema NOT IN ('pg_catalog', 'information_schema');
```

This query will display all the non-default (i.e. the ones that PostgreSQL itself made) tables. You should see an ouput something like this (I am running this against a correctly configured DB, there is bottom output that I truncated but the `augur_data` tables are the most important).

Screen Shot 2020-03-21 at 10 53 09 PM
 
If you're using a graphical UI to manage your database, you should just be able to view all the table using your tool of choice.

**Comment by manangoel99** [comment]
@ccarterlandis I also assumed that ```make install```  would take care of that but it set up only a couple of the tables. I then ran the 
```
augur db create-schema
augur db load-data``` 
commands when I couldn't figure out anything else. That seemed to work and correctly configure the database.

**Comment by ccarterlandis** [comment]
@manangoel99 oh good, I am glad to hear those commands worked. Sorry you were facing issues with that process, I actually rewrote the install script last night to (hopefully) be more robust. The work has not been merged into `dev` yet but it will be soon. 

We are also deprecating the use of the `augur db load-data` command, as we are moving to using Docker containers for our sample data. It will still work just fine in `dev`, but be warned the data is pretty out of date and we've made some big changes to our schema since the last time the sample data is generated (for example, the `repo_badging` table is completely different and is incompatible with the data that the `load-data` command used). Sorry again for all the confusion, and thanks for your contributions!! Let us know how we can continue to support you going forward 😊

**Comment by manangoel99** [comment]
@ccarterlandis How far along is the work on using Docker Containers for sample data. I have worked with docker before and I'd be to happy to contribute to that.

**Comment by ccarterlandis** [comment]
It's been completed, you can find out more about using our Docker container [here](https://oss-augur.readthedocs.io/en/doc-a-thon/docker/toc.html) and more specific information about the test container [here](https://oss-augur.readthedocs.io/en/doc-a-thon/docker/toc.html). These documentation links are still a work in progress, so my apologies if they are incorrect.

**Pull request merged**
