### PR TITLE
Add CII Panel

### PR DESCRIPTION
**Pull request by Nebrethar**
This pull request is to add CII best practices metrics to the augur Risk dashboard.

image

### CODE REVIEW

**Comment by sgoggins** [comment]
@ccarterlandis : Can you look into why the Travis-CI build is failing on this. @Nebrethar : Probably helpful if you look at the build log as well. I think this might be an issue where PR's always fail but I am not sure.

**Comment by sgoggins** [comment]
@ccarterlandis : Its the API tests that are failing .. I remember you mentioning an issue there earlier this week. I want @gabe-heim  to look at this, but its important for the Risk group so if there's stuff we need to ask @Nebrethar to change I would like to get that info to him ASAP.

**Comment by Nebrethar** [comment]
Closing this because it needs to include more augur repositories to prevent stalling issues.

**Comment by Nebrethar** [comment]
Will reopen at a more mature stage of development

**Comment by gabe-heim** [comment]
@Nebrethar What do you mean "needs to include more augur repositories"? What does? Regardless of that, the current changes proposed in this PR are beneficial and I'd be happy to merge if you are wanting to reopen, but if not just reopen when you are happy with the changes

**Comment by Nebrethar** [comment]
@gabe-heim I am currently working on some fixes to bugs this update would introduce. The one I haven't fixed yet is that CII metrics present on the page will prevent the page from loading if there is no CII data returned. I didn't want to put that on dev until it's fixed..

**Comment by Nebrethar** [comment]
I reopened this because the loading issues have been fixed. The page will not fail to load; Instead, it will load everything but the CII panel.

I can also make it so that the CII panel loads, but states that it has no data. Let me know if you have a preference.

A great repo to try CII badging out on is `zephyrproject-rtos/zephyr`

**Comment by gabe-heim** [comment]
Stating that the CII panel did not not return any data for this repo is a preferable solution rather than just not rendering the panel at all. I will work on #370 if you want to update this in the meantime, if you are having trouble figuring out how to do that let me know.

**Comment by Nebrethar** [comment]
This branch has a default CII panel now that mentions that there is no CII data available.

**Pull request merged**
