### PR TITLE
augur user add cli commands fixed

### PR DESCRIPTION
**Pull request by Priya730**
Signed-off-by: Priya Srivastava <shivikapriya730@gmail.com>

**Description**
- The changes were required as the current work does not import User model, engine sessions and admin flag does not match with the current schema. Command now also requires firstname and lastname arguments.

image

NOTE: **admin attribute not present in the current schema**
This PR fixes:
1. Imported engine and User., session fixed.
2. Changed echo message

**Notes for Reviewers**
This PR is continues the changes made by #1912

**Signed commits**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Priya730** [comment]
@Ulincsys please review this PR

**Comment by Priya730** [comment]
Also, can you tell me how to integrate the admin flag to the current schema

**Comment by sgoggins** [comment]
@Ulincsys : Can you review this?

**Review by Ulincsys — CHANGES_REQUESTED** [review]
I think that the add user command will fail without adding the admin argument in the call to construct the `User` object (since that column has a NOT_NULL constraint). I see that the command line option for this was commented out.

**Comment by Priya730** [comment]
> I think that the add user command will fail without adding the admin argument in the call to construct the `User` object (since that column has a NOT_NULL constraint). I see that the command line option for this was commented out.

Yes I realised that and was doing the same changes right now

**Review by Ulincsys — APPROVED** [review]
Looks good!

**Pull request merged**
