### PR TITLE
Completed the microtasks

### PR DESCRIPTION
**Pull request by Adarsh-NP**
Had completed it way back and confirmed with Carter but had forgotten to push the files, sorry for that.
It also has an experimental set-up of a worker that adds the information about latest commits on my test-repository on gitlab in a psql database named commits.

### CODE REVIEW

**Comment by ccarterlandis** [comment]
Hey @Adarsh-NP, thanks for submitting your microtasks. The code looks good to me, but can you shorten the name of the subfolders - perhaps to `database_demo` and `api_demo` or something like that? You can use whatever names you like, but having long folder names can make things harder to read if they're too long and can be an inconvenience when displayed on smaller screen sizes like a laptop.

**Comment by Adarsh-NP** [comment]
Oh I am so sorry, I should have taken care of that...thanks for telling.

**Comment by Adarsh-NP** [comment]
@ccarterlandis  the sign-off thing seems to not work for me. I tried what's there in the DCO document, earlier it worked...but now its not working...I am sorry if I am making some extremely small mistake but please help.

**Comment by Adarsh-NP** [comment]
Oh that was some carelessness from my side. Thanks

**Comment by Adarsh-NP** [comment]
Oh, I am really sorry about that (awkward face). i'll do that.

**Comment by ccarterlandis** [comment]
@Adarsh-NP according to the DCO check:
> Commit sha: [2036514](https://github.com/chaoss/augur/pull/638/commits/20365141ad7d2face5cb42c8e349920bbeabf80a), Author: Adarsh, Committer: Adarsh; The sign-off is missing.

The commit log shows the message being formatted like this:
```
ommitted the folders
Signed-off-by: Adarsh <f20180806@goa.bits-pilani.ac.in>
I think the DCO bot expects there to be an empty line before the sign-off. Try adding it and that'll probably fix it, since there are no other commits missing a sign-off.

**Comment by Adarsh-NP** [comment]
The DCO thing is still not working, I don't know what to do. Kindly help @ccarterlandis .

**Comment by ccarterlandis** [comment]
It looks like the same commit is still failing. What happens when you run the commands provided by [the DCO check](https://github.com/chaoss/augur/pull/638/checks?check_run_id=545366523)?

**Comment by Adarsh-NP** [comment]
signoff

**Comment by mrsaicharan1** [comment]
Commit history needs to be fixed here!

**Comment by Adarsh-NP** [comment]
Hello @mrsaicharan1 , thanks for your help but can you please elaborate on it bit more. I didn't get how to fix it.

**Pull request merged**
