### PR TITLE
Add Metric Status Worker and Translate Repo function in AugurAPI.ts

### PR DESCRIPTION
**Pull request by bing0n3**
- Add a Metric Status Worker that parse markdown and source code to generate metric status. 
- Translate Repo function to `Repo` class and create a new `RepoGroup` class

### CODE REVIEW

**Comment by bing0n3** [comment]
@sgoggins : I will finish the integrated work tomorrow and write an instructor. I took a day to learn how housekeeper and broker work.

**Comment by bing0n3** [comment]
@sgoggins : I have added a readme.

**Comment by sgoggins** [comment]
@gabe-heim : Could you review the typescript part of the pull request? I want to make sure what you are doing right now is coordinated with this PR.

**Comment by gabe-heim** [comment]
Looks great and very well thought out thank you Bingwen

**Pull request merged**
