### PR TITLE
Release v0.14.0

### PR DESCRIPTION
**Pull request by sgoggins**
# CHANGELOG

- Schema updated to version 26
- Minor documentation updates
- Implement `GET` request response for every worker's `/AUGWOP/task` route
- Implement data collection status endpoints under `/api/unstable/collection_status`
- Add SPDX license identifiers to source code files
- Add `augur backend` family of commands to replace `augur run`
- `augur util` commands for process control moved to `augur backend` group
- `augur configure generate` renamed to `augur config init`

### CODE REVIEW

**Comment by ccarterlandis** [comment]
Huh, I have no idea what could have possibly caused that issue with #956, although I am certain it was not our fault and instead a problem on Travis' end. Since this one works I won't worry further, but if it happens again I'm going to file a bug report on Travis.

**Comment by ccarterlandis** [comment]
Marked this as a draft until it's ready to be merged.

### TODO before marking as ready for review:

- [ ] - CHANGELOG
- [ ] - Double check update CLI docs
- [ ] - Update test data

**Comment by sgoggins** [comment]
@ccarterlandis : When do you think we will be executing this release?

**Comment by ccarterlandis** [comment]
@sgoggins Hard to say for sure. I'd probably say tomorrow afternoon at the absolute earliest, but that's not a guarantee. Why do you ask?

**Comment by ccarterlandis** [comment]
@sgoggins now we are just waiting on #959 and #960 to pass - then we can merge them, make sure this PR build passes, and then release.

**Comment by sgoggins** [comment]
@ccarterlandis / @gabe-heim : I think there are two PR's open that, if they get merged, will make the release ready.

**Comment by sgoggins** [comment]
Closing because of TRAVIS-CI bug. Will Reopen.

**Comment by ccarterlandis** [comment]
Uh, what? There is no Travis CI bug on this PR, both checks passed succesfully. Please reopen this PR.

**Comment by ccarterlandis** [comment]
Once the checks pass, this PR is ready for review.

**Review by gabe-heim — APPROVED** [review]
LGTM

**Comment by ccarterlandis** [comment]
Closed and then re-opened to try and fix this stupid Travis PR issue...

**Review by ccarterlandis — APPROVED** [review]
LGTM

**Review by ccarterlandis — APPROVED** [review]

**Review by gabe-heim — APPROVED** [review]

**Pull request merged**
