### PR TITLE
Merging dev to master

### PR DESCRIPTION
**Pull request by sgoggins**

### CODE REVIEW

**Comment by sgoggins** [comment]
@ccarterlandis @gabe-heim ; I have resolved all the merge conflicts on my computer at home .... I need a review to push the changes.

**Comment by sgoggins** [comment]
@germonprez @klumb @ccarterlandis @gabe-heim : I need an approval so I can push the merge conflicts I resolved locally. Which seems like a bass-ackwards process ... but that's what we have setup.

**Comment by germonprez** [comment]
@sgoggins does this need a DCO from you?

**Comment by sgoggins** [comment]
@germonprez : Hmmm ... I DCO's it earlier ... but now its DCO'd either "again" or "actually, because ma brain broke!"

**Comment by germonprez** [comment]
conflicts now. can't merge

**Pull request merged**
