### PR TITLE
add rabbitmq docker configuration

### PR DESCRIPTION
**Pull request by GaryPWhite**
**Description**
- adds configuration for rabbitmq within docker compose files

**Notes for Reviewers**

**Signed commits**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by GaryPWhite** [comment]
if we don't want the rabbitmq credentials to be out and about in the compose file, we may need to add something to the scripts that set up docker. Let me know if that's preferable, or if this is fine as-is!

**Comment by sgoggins** [comment]
@GaryPWhite : Our automated docker build seems to not like some aspect ... though I suspect this is an idiosyncracy that might be easily fixed? 

```
#6 [2/4] COPY --chown=rabbitmq:rabbitmq augur.conf /etc/rabbitmq/conf.d/
#6 ERROR: failed to calculate checksum of ref 625296d6-9be1-4356-a58b-91c3a8df5f0b::vijqe506c466y2g2arus31hxl: "/augur.conf": not found

#7 [1/4] FROM docker.io/library/rabbitmq:3.12-management-alpine@sha256:28892f3ab8acefc71950a058dd50bace1cbbf28417649678180a2ce73995406f
#7 resolve docker.io/library/rabbitmq:3.12-management-alpine@sha256:28892f3ab8acefc71950a058dd50bace1cbbf28417649678180a2ce73995406f done
#7 sha256:f961ab691b2c344fffdc5ff90772bf0a5c011399ed1234e9c7bdce96fda9996c 3.28kB / 3.28kB done
#7 sha256:28892f3ab8acefc71950a058dd50bace1cbbf28417649678180a2ce73995406f 8.86kB / 8.86kB done
#7 sha256:13de8e3bac800bb3e2176bf8ab922eaf7380a6c4722024c7e0e98c3b41e84a9e 10.66kB / 10.66kB done
#7 CANCELED
------
 > [2/4] COPY --chown=rabbitmq:rabbitmq augur.conf /etc/rabbitmq/conf.d/:
------
Dockerfile:6
--------------------
   4 |     LABEL version="0.62.0"
   5 |     
   6 | >>> COPY --chown=rabbitmq:rabbitmq augur.conf /etc/rabbitmq/conf.d/
   7 |     
   8 |     RUN chmod 777 /etc/rabbitmq/conf.d/augur.conf
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 625296d6-9be1-4356-a58b-91c3a8df5f0b::vijqe506c466y2g2arus31hxl: "/augur.conf": not found
Error: Process completed with exit code 1.
```

**Comment by sgoggins** [comment]
> if we don't want the rabbitmq credentials to be out and about in the compose file, we may need to add something to the scripts that set up docker. Let me know if that's preferable, or if this is fine as-is!

I think it would be optimal if we advised people to create a file called `env.list` that loaded the environment variables we ask for, and then also the RabbitMQ requirement variables. @GaryPWhite

**Comment by GaryPWhite** [comment]
> @GaryPWhite : Our automated docker build seems to not like some aspect ... though I suspect this is an idiosyncracy that might be easily fixed?
```

Yeah seems likely that I missed something about how the CI builds / runs. I'll give it another swing.

**Comment by GaryPWhite** [comment]
@sgoggins - I looked through documentation in the repo and tried to do this in a way consistent w/ the rest of the environment variables -- let me know if there's anything else you would like to see.

**Comment by sgoggins** [comment]
@GaryPWhite : heyOH! Container builds on GitHub! W00t!!

**Review by sgoggins — APPROVED** [review]

**Pull request merged**
