### PR TITLE
[GSoC Microtask] Added visualization for previous message anomalies 

### PR DESCRIPTION
**Pull request by aksh555**
As suggested earlier, I have added a chart to give more insight.
I was also wondering if the messages and issues table could be merged by issue id to get more insights..
Please suggest any improvements needed

### CODE REVIEW

**Comment by gabe-heim** [comment]
In regards to your question about joining issues and messages, the `issue_message_ref` table is a relational table between the `issues` and `message` tables. Here is some sql that will connect the tuples of each using that relational table:

```
SELECT * 
FROM issues, issue_message_ref, message
WHERE issues.issue_id = issue_message_ref.issue_id
AND message.msg_id = issue_message_ref.msg_id
AND repo_id = 25158
LIMIT 10
```

With regards to your notebook, the message analysis is really interesting @aksh555 ! I could see this being part of the insight (anomaly) worker at some point, which is located in the `workers/insight_worker` directory if you are interested in seeing how I integrated the contents of the other anomaly detection notebook for time series anomalies. 

Just so I have a better understanding, what fields/aspects of a message is your model using to determine if it is anomalous? Does it have to do with your most/least frequent word counts?

**Comment by aksh555** [comment]
Yes @gabe-heim, It is based on the common idea of seeing which messages have the least frequently occurring words in them, to classify as anomalous. 
By merging messages with the issues table, I was thinking some more analysis on the activity of an open issue could be provided, based on the kinds of messages(comments) it receives, along with other factors.

**Comment by aksh555** [comment]
@gabe-heim @sgoggins @germonprez  
I have submitted my work on the micro-tasks, I would be glad to add on any further improvements or additional analysis which would help
Additionally, I would like to work on some tasks which would help in learning and understanding the Augur engine and workers as that would help me gain a better understanding of the project. Any starting ideas would really help :smile:

**Comment by germonprez** [comment]
Thanks @aksh555 -- make sure to follow this link to get the work submitted and documented: 

https://github.com/chaoss/governance/blob/master/GSoC-interest.md

**Pull request merged**
