### PR TITLE
Added SPDX license identifiers.

### PR DESCRIPTION
**Pull request by ajeurkar**
Fixes issue - #943 
@ccarterlandis @sgoggins @gabe-heim 
Added SPDX license identifiers to all the source code files except for the `*.sh` files.

### CODE REVIEW

**Comment by ajeurkar** [comment]
@sgoggins @gabe-heim @ccarterlandis Can I please get a review for the changes done.

**Comment by ccarterlandis** [comment]
@ajeurkar so sorry, yes I'll leave my review later today. Things got a bit busy with school earlier this week and I missed the notification that this PR came through! Thanks for your patience 😄

**Review by ccarterlandis — DISMISSED** [review]
LGTM! Thanks again for your help @ajeurkar! 🚀

**Review by ccarterlandis — APPROVED** [review]
Approving again because I forgot to change the base branch. We'll be doing a small bug-fix release soon, so we'll push these changes with those as well.

**Comment by ajeurkar** [comment]
@ccarterlandis Thank you so much. Would really appreciate if you can add a `hacktoberfest-accepted` label once the PR gets merged.

**Comment by ccarterlandis** [comment]
Hmmm, I can't merge it just yet. Looks like @gabe-heim will need to review since he is the codeowner for the frontend files. Gabe, when you get a chance, can you give this a quick once-over and leave your review? 

@ajeurkar thanks for the reminder. I'll go ahead and do it now before it's merged, since I already approved it and we just need @gabe-heim's review to satisfy the branch protection rules we use.

**Comment by ccarterlandis** [comment]
Is there anything else I need to do for you for Hacktoberfest @ajeurkar?

**Comment by ajeurkar** [comment]
@ccarterlandis  That's all.Thanks again and please feel free to share if there are any good first issues or something I can work on... :)

**Comment by ajeurkar** [comment]
> @ajeurkar so sorry, yes I'll leave my review later today. Things got a bit busy with school earlier this week and I missed the notification that this PR came through! Thanks for your patience smile

**Comment by ajeurkar** [comment]
Sorry! My bad... I mistakenly closed the PR :D

**Comment by ccarterlandis** [comment]
No worries, I've done it plenty of times myself 😆 

As for other first issues, I'd say [the other Hacktoberfest issues](https://github.com/chaoss/augur/labels/Hacktoberfest%202020) are a good place to start, but if there's some specific Augur component or perhaps language/skill you'd like to work on, I am more than happy to help you brainstorm other projects to work on!

**Comment by ajeurkar** [comment]
@ccarterlandis I am mainly working with Javascript/Typescript, Angular, Asp.Net, etc. But I would like to explore Augur component and see if I can contribute in anyway 😄

**Review by sgoggins — APPROVED** [review]

**Comment by sgoggins** [comment]
@gabe-heim : This needs your review.

**Comment by sgoggins** [comment]
@ccarterlandis : sorry, you need to approve again.  All I did was fix a merge conflict in the Makefile.  I went with what is in `dev`. Seemed smart.

**Review by ccarterlandis — APPROVED** [review]

**Pull request merged**
