### PR TITLE
Added PR metric - Closed PRs which weren't merged

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Added GitHub PR metrics - Closed PRs which weren't merged.
Added entry in API docs too

Signed-off-by: Saicharan Reddy: saicharan.reddy1@gmail.com

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@sgoggins @Nebrethar Please have a look at this

**Comment by mrsaicharan1** [comment]
It seems that the tests are failing for other reasons such as `augur.config.json` error.

**Comment by mrsaicharan1** [comment]
@ccarterlandis Hi, I'm not sure why travis is failing here.. Could you please help me out?

**Comment by ccarterlandis** [comment]
Please see my other comment on #560 explaining the build failure 👍

**Comment by mrsaicharan1** [comment]
@ccarterlandis Yeah! Also, It would be great if you could review the logic alluding to this PR.

**Comment by ccarterlandis** [comment]
@sgoggins is the one who has been spearheading our GSoC efforts this year so I would like to let him review any PRs until I've had a chance to talk with him to make sure we're on the same page. It's Saturday afternoon here in the US, so it could be a day or two until we have a chance to review all the PRs. We appreciate your patience and we promise we get to it when we can. 😄

**Comment by mrsaicharan1** [comment]
> @sgoggins is the one who has been spearheading our GSoC efforts this year so I would like to let him review any PRs until I've had a chance to talk with him to make sure we're on the same page. It's Saturday afternoon here in the US, so it could be a day or two until we have a chance to review all the PRs. We appreciate your patience and we promise we get to it when we can. 😄

Definitely! I'm on the central timezone as well so I definitely understand that :D.

**Comment by ccarterlandis** [comment]
Oh no way, I just saw your location!! I'm actually from Dallas myself 😍

**Pull request merged**
