### PR TITLE
refactor metrics and add routes

### PR DESCRIPTION
**Pull request by bing0n3**
* Refactored the 'New Contributors of Issues' metric to accept repo_group_id and repo_id instead of repo_url
* add  unit testing for metric 'New Contributors of Issues'

### CODE REVIEW

**Comment by sgoggins** [comment]
@bing0n3 and @parthsharma2 : Can you help us figure out which parts of the conflicts to keep. I think the augur_db.py looks pretty straightforward, but the differences in routes.py are more difficult for me to figure out.

**Comment by bing0n3** [comment]
@sgoggins Done. Check it.

**Comment by parthsharma2** [comment]
@bing0n3 [this commit](https://github.com/chaoss/augur/pull/292/commits/445ff606882b30b047251877d98cc05a0d2a26cf) seems to have changed some of the formatting of docstrings in the routes file [i.e. a newline after `@apiDesciption` to separate the `@apiParam`]. I'm not sure if it affects the automated creation of docs :sweat_smile:. Otherwise it all seems fine to me @sgoggins

**Comment by bing0n3** [comment]
@parthsharma2 : I generated an apidoc json, it looks good.

**Comment by parthsharma2** [comment]
@sgoggins the `routes.py` file seems all good now

**Pull request merged**
