### PR TITLE
Implement Evolution & Risk Metrics

### PR DESCRIPTION
**Pull request by parthsharma2**
Implemented the following metrics:

- **Evolution**
  -  _Issue Duration_: returns the duration of all closed issues
  -  _Issues Active_: returns a timeseries of the number of issues active per period (day, week, month, year). An issue is active if an issue event occurs.
 
- **Risk** _[Need Feedback]_
  - _CII Best Practices Badge_: returns the badge level.
  - _Languages_: returns the implementation languages. In this implementation, data is fetched from the repo_badging table. [Alternative source: repo table i.e. GitHub API based, but only stores primary language]
  - _License Declared_: returns the license declared. In this implementation, data is fetched from the repo_badging table. [Alternative source: repo_info table i.e. GitHub API based]

### CODE REVIEW

**Comment by sgoggins** [comment]
@parthsharma2 : I think we should pull the primary github declared language.  The badging app does not have very good coverage. Can you make that change?

**Comment by sgoggins** [comment]
I guess to do that, we would need to add something to pull that data placed into the GitHub worker. Since @gabe-heim is actively debugging that worker right now, we should get his input.  Do you know what API gets called to pull the primary language? 

Alternately, I have a version of the database for which I've done a full language analysis using the SCC project ... Lets see what @gabe-heim says about getting that data.

**Comment by parthsharma2** [comment]
@sgoggins `api.github.com/repos/:owner/:repo` endpoint can be used to get the primary language, it can also be used to get data (such as forks, stars, license, etc.) for the repo_info table. If you want to get all the languages you can use `api.github.com/repos/:owner/:repo/languages`

**Comment by parthsharma2** [comment]
@sgoggins I've made the changes to the 'languages' metric implementation. I used git rebase to edit the particular commit to make changes. I've somehow become a co-author of certain commits although locally none of those commits mention me as an author. Any way to solve this :confused: @gabe-heim @sgoggins ?

**Comment by gabe-heim** [comment]
Btw this can definitely be added to the github worker, it would just be in a separate method of the worker and probably be viewed as a different "model" that the worker can fulfill

**Comment by parthsharma2** [comment]
@sgoggins @gabe-heim maybe I can give it a try?

**Comment by gabe-heim** [comment]
@parthsharma2 Definitely! Go for it

**Comment by gabe-heim** [comment]
Depending on what @sgoggins wants

**Pull request merged**
