### PR TITLE
Implement metrics in githubapi

### PR DESCRIPTION
**Pull request by parthsharma2**
Implemented the following metrics:

- **Code Commits:** This implementation returns the number of code commits per day.
- **Contributors:** This implementation returns a list of contributors along with their respective contributions to a project.

### CODE REVIEW

**Comment by parthsharma2** [comment]
Hey @ccarterlandis, the Travis CI builds of my PRs keep on failing. On checking the build logs seems like there is some issue connecting to the database in the builds resulting in various errors.

Am I doing something wrong?

**Comment by ccarterlandis** [comment]
Sorry to hear that you're having trouble, @parthsharma2. Has it been working up to this point? Because I have a hunch as to what the problem might be, but just for sanity's sake, could you tell me what happens when you run `make dev`? Feel free to just post a screenshot or c/p the logs, whatever you prefer!

**Comment by parthsharma2** [comment]
On running `make dev` i get the following `make: conda: Command not found` since i'm not using anconda and have set up my own python virtual environment :sweat_smile:

On the other hand on further examining the Travis CI build logs the following line caught my eye `Encrypted environment variables have been removed for security reasons` and lead me to https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions. I think the following quote from the documentation might be the reason 

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

> Pull requests sent from forked repositories do not have access to encrypted variables or data.

**Comment by ccarterlandis** [comment]
I didn't know about that, but that makes perfect sense! All of our builds are passing, and if I remove all the configured environment variables and run the tests I get similar errors. I say we chalk it up to this and not worry too much about it. 😉 

Have you run into any problems not using Anaconda? We have been considering ditching it since it's kinda annoying to work with, I'm curious to hear about your mileage.

**Comment by parthsharma2** [comment]
Currently, I've only been playing around with `datasources.githubapi` and it seems to be working well till now. I'll experiment a bit more and let you know. And also a +1 for ditching Anaconda.

**Comment by parthsharma2** [comment]
Everything seems to be working fine in the virtual environment. The server's working, the routes are being made, the endpoints are working and the metrics statuses are being displayed. 

Only parts dependent upon Anaconda such as the make file need to be changed.

**Comment by sgoggins** [comment]
@ccarterlandis : I took a look at what this pull request is doing and its using the GitHub API.  I have not configured Travis at all, so my question may be naive ... but do we have a GitHub API Key in the travis build?

**Comment by sgoggins** [comment]
@ccarterlandis and @parthsharma2 : I do think its a GitHub API Key configuration in TRAVIS issue. (i.e., the issue is NOT the code that @parthsharma2 submitted, but our Travis config.)

Here's the bottom of the log: 

[1m[31mE           KeyError: 'data'[0m

[1m[31maugur/datasources/githubapi/githubapi.py[0m:265: KeyError
---------------------------- Captured stderr setup -----------------------------
2019-01-25 10:57:43 travis-job-3cafaeb8-c86b-423c-9509-397bfd357318 augur[3669] ERROR /home/travis/build/chaoss/augur/augur.config.json could not be parsed, using defaults. Fix that file, or delete it and run this again to regenerate it. Error: Expecting value: line 1 column 1 (char 0)
application.py              67 ERROR    /home/travis/build/chaoss/augur/augur.config.json could not be parsed, using defaults. Fix that file, or delete it and run this again to regenerate it. Error: Expecting value: line 1 column 1 (char 0)
------------------------------ Captured log setup ------------------------------
application.py              67 ERROR    /home/travis/build/chaoss/augur/augur.config.json could not be parsed, using defaults. Fix that file, or delete it and run this again to regenerate it. Error: Expecting value: line 1 column 1 (char 0)
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
application.py             119 DEBUG    {plugin_name} plugin loaded
__init__.py                 18 DEBUG    Initializing GitHub API
------------------------------ Captured log call -------------------------------
connectionpool.py          813 DEBUG    Starting new HTTPS connection (1): api.github.com:443
connectionpool.py          393 DEBUG    https://api.github.com:443 "POST /graphql HTTP/1.1" 403 None
[31m[1m===================== 34 failed, 1 passed in 22.35 seconds =====================[0m
travis_time:end:0274a67c:start=1548413841738971342,finish=1548413864612720153,duration=22873748811
[0K[31;1mThe command "python -m pytest augur/datasources/**/test_**.py" exited with 1.[0m



Done. Your build exited with 1.

**Comment by ccarterlandis** [comment]
@sgoggins: @parthsharma2 and I chalked the issue up to this, from the Travis docs as pointed out by @parthsharma2: 

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.
Pull requests sent from forked repositories do not have access to encrypted variables or data.

Since @parthsharma2 is making the commits from his repository and not ours, he doesn't have access to those encrypted variables (including the GitHub API key), meaning that **no matter what he does**, the tests won't pass on his branch. As a result, I'm going to go ahead and merge these changes and then run the build again and see if it'll pass. If it doesn't, we'll fix it!

**Pull request merged**
