### PR TITLE
Optimize core recollection

### PR DESCRIPTION
**Pull request by ABrain7710**
**Description**
- Please include a summary of the change.

This PR fixes #

**Notes for Reviewers**
- This should not be merged until optimize secondary recollection pr is merged

**Signed commits**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sgoggins** [comment]
@ABrain7710 : what's the status of this one?

**Comment by sgoggins** [comment]
@ABrain7710 : What's the status of this one with regards to testing? Should we merge it now that we have done a release.

**Comment by ABrain7710** [comment]
This one is in progress and dependent on the GitHub paginator changes to work

**Comment by sgoggins** [comment]
@ABrain7710 : Is this ready?

**Comment by sgoggins** [comment]
> This one is in progress and dependent on the GitHub paginator changes to work

Those are the ones we are currently testing in `dev`, or that we released last week?

**Comment by ABrain7710** [comment]
No this is not ready. It is dependent on the changes that are in dev and needs some changes to use those

**Pull request closed without merging**
