### PR TITLE
feat: Added configuration support for GitLab API keys

### PR DESCRIPTION
**Pull request by mrsaicharan1**
This PR includes the Gitlab data collection setup as a part of the config generation process. Aids in providing the Gitlab access keys as a CLI param.
As mentioned by @sgoggins, a follow-up PR would be required to store multiple keys in the `worker_oauth` table present in the `augur_operations` schema.

### CODE REVIEW

**Comment by sgoggins** [comment]
@mrsaicharan1 : Can you do this from your branch into the `dev` branch? 

Our process is --developer -> dev --> testing --> master

**Comment by sgoggins** [comment]
@mrsaicharan1 : NEVERMIND ... I was able to edit the PR myself!

**Comment by mrsaicharan1** [comment]
@sgoggins Yeah! I forgot about the base branch. I was trying to figure out why I had so many unrelated commits. Got it now!

**Comment by mrsaicharan1** [comment]
In addition to that, I see that there's a labeler check failing. Could you point me to the labeling guidelines?

**Comment by sgoggins** [comment]
@mrsaicharan1 : Would it be possible for you to do an additional pull request that documents where one goes to get their gitlab API key? @ccarterlandis : I think we provide that link for GitHub in our docs, don't we?

**Comment by sgoggins** [comment]
Officially, @ccarterlandis 's review is the only one I care about. If @ccarterlandis is good with it, kick the tires and light the fires!  (see "Top Gun Film").

**Comment by sgoggins** [comment]
@mrsaicharan1 Something about that labeler check is always failing ... so right now we are ignoring it ... its a new check we are trying to get going, but its a bit finicky.

**Comment by ccarterlandis** [comment]
The labeler check is not failing because it's finicky, it's failing because @mrsaicharan1's PR is coming from a fork. Due to the way GitHub Actions are implemented, PRs coming from forks will not have the required permissions to tag issues with labels. There's nothing we can do about it, but the check exists only to add labels to issues where appropriate, so nothing is "broken" and the check can be ignored. For future reference @sgoggins, this will **always happen on any PR coming from a fork**. To reiterate, unless GitHub changes how they do Actions integrations, there is nothing we can do about this, but nothing is actually broken.

**Comment by mrsaicharan1** [comment]
@ccarterlandis Yeah! I guess that makes sense. Just an fyi, I was following the semantic labeling rules!
https://seesparkbox.com/foundry/semantic_commit_messages

**Comment by mrsaicharan1** [comment]
@ccarterlandis Edited the installer script `config.sh` & also updated the documentation to point the readers to access keys page!

**Comment by mrsaicharan1** [comment]
@gabe-heim @ccarterlandis The configuration support is required for the gitlab worker. Ergo, If this is GTG, you can go ahead and merge it :).

**Pull request merged**
