### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Nayan-Das**
GSOC & Outreachy SSO Microtasks #557

I have completed microtask 0 1 and 2.
This is a very simple facebook based SSO authentication.
 The other two methods "Google and Twitter " are not implemented yet.
There is also a normal login method with the user name and password as "nayan".

### CODE REVIEW

**Comment by ccarterlandis** [comment]
Hey @Nayan-Das, thanks for completing this microtask. I'll have a chance to review it later today, I just need to finish up some other things first. Please don't hesitate to ping me if I forget 😁

**Comment by sgoggins** [comment]
@Nayan-Das : Need you to do a DCO sign off on the commit. 
@michaelwoodruffdev : Can you review the contents of this pull request. Mainly I would like to know if it breaks anything, or if we should create a separate branch for it.

**Comment by Nayan-Das** [comment]
I am creating a new pull request with DCO.

**Comment by Nayan-Das** [comment]
I have created a new pull request with DCO.

**Pull request closed without merging**
