### PR TITLE
used isolation forest model for anomaly detection

### PR DESCRIPTION
**Pull request by ishagarg06**
Worked on annual dm_repo dataset. Visualised the model by applying seaborn packages. Build the model and detect the anomalies using isolation forest.
Please review it once :)
Thanks!

### CODE REVIEW

**Comment by ishagarg06** [comment]
When I submit a PR it's showing some checks are not successful.
https://github.com/ishagarg06/augur/blob/dev/notebooks/ishagarg06_Anomaly_detection.ipynb
Here is the link of my work on anomaly detection. Please have a look. And suggest me what can do to regarding DCO as PR is not successful.

**Comment by pratikmishra356** [comment]
@ishagarg06 Before commit you need to sign off first
 click above on "DCO" details you will see this
Screen Shot 2020-03-29 at 8 21 30 PM

run those commands as mentioned

**Comment by ccarterlandis** [comment]
Thanks for your submission @ishagarg06, we will review it as soon as we can 😁

**Comment by ishagarg06** [comment]
@ccarterlandis So shall I recommit along with sign off?  And then create a new PR?

**Comment by mrsaicharan1** [comment]
Just change the base branch to which you're trying to make the change and you're GTG!

**Comment by ishagarg06** [comment]
@mrsaicharan1 That means I have to commit again on different branch. And no need to create a new PR?

**Comment by mrsaicharan1** [comment]
Nah not required. Run for `git commit -s --amend`.
Enter a new message and `git push -f`

**Comment by ishagarg06** [comment]
@mrsaicharan1 Still some checks were not successful.? Shall I repeat that again.?

**Comment by mrsaicharan1** [comment]
there's changes from other PRs as well -- the commit history is messed up in this PR.
So the best option would be to apply use git stash!

Firstly, add a remote.
`git remote add upstream https://github.com/chaoss/augur`
Then, as you have your changes in the preivous '1' commit,
`git reset HEAD~1`
Then,
`git status`
Your changes are seen in red
perform a git reset,
`git reset --hard upstream/GSoC`

Now apply your stored stash
`git stash apply`


Great! Now you've fixed your commit history!
Just do the ordinary at this point!
`git add .`
`git commit -s -m <your_message> `
`git push -f origin dev`

**Comment by ishagarg06** [comment]
@mrsaicharan1 After the changes were in red, when I run git reset `git reset --hard upstream/GSoC` following error displayed.
`fatal: ambiguous argument 'upstream/GSoC': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

**Comment by mrsaicharan1** [comment]
Maybe try upstream/dev

**Comment by ishagarg06** [comment]
Again! the same error.

**Comment by mrsaicharan1** [comment]
> Again! the same error.

Oops, forgot one command in between. You need to fetch the remote branches!
`git fetch`

**Comment by ishagarg06** [comment]
Nothing worked. Same error again. Now I should create a new PR that's the only option left.
Anyways.. Thankss a lot.!! @mrsaicharan1

**Comment by ishagarg06** [comment]
@sgoggins Sir in DCO it's mentioned that
`Commit sha: f48ec8e, Author: Sean P. Goggins, Committer: GitHub; The sign-off is missing.`
Could you please help in fixing this.

**Pull request merged**
