### PR TITLE
WIP: Documenation rewrite

### PR DESCRIPTION
**Pull request by ccarterlandis**
## The contents of this pull request are currently under heavy development and are NOT ready to be merged.

This PR introduces a near-complete rewrite of Augur' s documentation.

It currently includes rough drafts of:
- A "Getting Started" guide with the details the database setup, installing Augur for production, and configuring the data collection workers for production
- The "Getting Started" section of for new Docker images
- Instructions for building, running, and using the Docker containers
- Instructions for installing and configuring Augur for local development
- Usage documentation for Augur's `Makefile`

Currently under development:
- An `augur.config.json` reference document
- Usage documentation for Augur's command line API
- Edits to the `README.md` and `CONTRIBUTING.md`

This PR is mainly for providing a centralized location to discuss and work on Augur's new documentation. 

Welcome to the Augur's first Doc-a-thon, Virtual Edition! 📖 🖊

### CODE REVIEW

**Comment by Adarsh-NP** [comment]
Hello guys, so I am working with another fellow aspirant on a  less error prone documentation while installing augur on the local machine. Kindly tell me how to see the latest update in this PR, as I don't yet know how to check on that. 
Will love to contribute in this ongoing PR.
Thanks in advance.

**Comment by ccarterlandis** [comment]
@Adarsh-NP Since you have been assigned to this PR, you'll get emails whenever there is activity on it (such as commits, comments, build status, etc), even if you are not specifically tagged.

**Comment by NodiraIbrogimova** [comment]
Hello,
Thanks for adding. The first version of documentation for less error installation has been completed. Would be great to have your review @ccarterlandis (or other reviewers).

**Comment by ccarterlandis** [comment]
@Adarsh-NP @NodiraIbrogimova I have pushed some updates to the documentation using some of the work you both did to make it less error-prone - thanks for doing that. I have not incorporated everything, as there are some things I'd like to work on and perhaps separate out first. 

I would appreciate it if you both could walk through the updated [getting started docs](https://oss-augur.readthedocs.io/en/doc-a-thon/getting-started/toc.html) and take notes on where it could be improved. None of the sections are finished (and some are just blank pages), but I would appreciate your candid feedback. 

There is also a new section about installing for development as well as a section about using Docker. If you want to test those as well, feel free, but I have not finished them so I can't guarantee their correctness. 😄

**Pull request merged**
