### PR TITLE
Anomaly Detection using Isolation Forest and OneCLassSVM on weekly_repo_dm [Gsoc]

### PR DESCRIPTION
**Pull request by pratikmishra356**
Signed-off-by: pratikmishra356 <mishrapratik356@gmail.com>
In this Notebook I did Data Analysis on Weekly_repo_data_metrics and then pointed out the outliers using Isolation Forest and SVM.
@ccarterlandis @gabe-heim please review this notebook and I also need ur guidance on approach for anomaly detection based on different use cases.
1 : Time Series Forecasting
2 : Real time anomaly detection for streaming Data.
These two methods seems useful for this "Anomaly Detection Project".
Screen Shot 2020-03-14 at 3 29 58 AM

### CODE REVIEW

**Comment by pratikmishra356** [comment]
@gabe-heim 
Currently augur is performing statistical method to point out anomalies and show anomalous insights across repos.
Can you please suggest some use cases upon which outliers should be detected as it would help in selecting machine learning algorithms ?.

**Comment by gabe-heim** [comment]
Hi @pratikmishra356 , thank you for your contribution! With regards to the use cases you brought up:
1. We currently do not see a use case for time series forecasting across open source time series metrics. We generally think of open source metrics as something that should be analyzed and not predicted, where you analyze activity and see what has gone wrong/right so that community managers can formulate plans that could improve things proactively, rather than attempting to predict activity and community managers formulating plans based off of a NN's predictions. This is why we are generally focusing on anomaly detection for our metrics, because we want to focus on pointing things out that would be startling and trigger a response that something needs to change.
2. We certainly have a use case for real-time anomaly detection, I will briefly outline our current methods to achieve this (they could be improved), but please don't hesitate to ask questions if it is not clear. Our insight/anomaly worker (located in `workers/insight_worker`) receives JSON tasks from the entities we named the housekeeper (regulates the creation of tasks) and broker (determines compatible workers and does the actual sending of the tasks to the workers). The insight worker hits a specified few metrics of our API for the repo of the task it receives, the default metrics to consider anomalies for have to do with issue, pull request, and commit counts. We have our issue, pull request, and commit data collection workers running nearly 24/7, which ensures that this data (and therefore the API endpoints that the insight worker is hitting) is up to date. The best way to see how it works it to run it yourself and check out the logs in `logs/backend.log` to see the broker/housekeeper activity, and `workers/insight_worker/worker_*port number*.log` to see the worker activity. If you want to run the insight worker locally, make the following alterations to your config:
This will tell the housekeeper to regulate the sending of a task for the `insights` model for every repo in the database (we signal to send a task for every repo by setting `repo_group_id` to 0):
```
"Housekeeper": {
        "jobs": [
            {
                "delay": 1000000,
                "given": [
                    "git_url"
                ],
                "model": "insights",
                "repo_group_id": 0
            }
        ]
    },
```

This may or may not already be in your config, but I will explain each parameter:
```
"insight_worker": {
            "port": 54335,
            "metrics": {"issues-new": "issues", "code-changes": "commit_count",
                       "reviews": "pull_requests", "contributors-new": "new_contributors"},
            "contamination": 0.041,
            "switch": 1,
            "workers": 3,
            "training_days": 365,
            "anomaly_days": 14
        },
```

`switch`: Turn this to `1` if you want to automatically start the worker. The alternative is to navigate to `workers/insight_worker` and run `insight_worker_start` in a separate terminal tab while Augur is running.
`workers`: the number of workers you want to automatically start when the `switch` is turned to `1`.
`port`: The starting port that the workers will live on. If the `workers` parameter is >1, then the port that the subsequent workers will live on port: value of the `port` parameter + `i` for the `i`th worker spawned.
`metrics`: For each repo/repo group the insight worker receives a task for, the worker will hit our api for each of the time series metrics provided in this parameter and will run our anomaly detection algorithm on each of them. They are provided in the format:
```
{
    'endpoint_name_1': 'field_1_of_endpoint',

    'endpoint_name_1': 'field_2_of_endpoint',

     'endpoint_name_2': 'field_1_of_endpoint',

    etc.

} 
```
`contamination`: "Sensitivity" parameter for detecting anomalies. Acts as an estimated percentage of the training_days that are expected to be anomalous. The default is 0.041 for the default training days of 365: 4.1% of 365 days means that about 15 data points of the 365 days are expected to be anomalous. We will eventually make this easier for users by allowing them to only have to enter a `number_of_expected_anomalies` parameter instead, so that they would not have to worry about performing the above "calculation".
`training_days`: The number of days to define what is normal for a metric, as well as the time period for detecting anomalies. Default is 365.
`anomaly_days`: Of the detected anomalies in the `training_days` , ones that fall within the most recent `anomaly_days` (default 14), will be logged in the database and sent as a notification through our slack bot.

**Comment by pratikmishra356** [comment]
Thanks @gabe-heim for your detail answer,I understood what you had said in 1st part and made me more clear about the goal of this project.
I would like to first try insight worker run locally and will reach you in case of any doubt.

**Comment by pratikmishra356** [comment]
Hi @gabe-heim I have few questions like 
1 : How housekeeper decides when and which task will be performed, does it automatically perform after some interval?
2 : For now we have _issues_, _contributers_, _commits_, _message_ and _pull request_ metrics some of which may require different algorithm to find insights and outliers,We should develop different models depending on metrics?
3 : I also want to know about how slack bot will send notifications?

**Comment by gabe-heim** [comment]
@pratikmishra356 
1 : The housekeeper generates a task for each repo in the specified repo group and tells the broker about each task 3 seconds apart (to keep things un-congested while keeping task efficiency unaffected). Every time a worker is booted, it sends a "hello" message to the broker so that the broker knows that worker exists, and that message includes information such as what data models (e.g. "insights") it can fill and what kind of input(s) (e.g. "git_url") it can take. When the broker learns of these tasks the housekeeper generated, the broker determines which worker(s) it is aware of that are compatible with the task (compatible data model and input), and puts the task in the queue it has allocated for the compatible worker with the fewest tasks in its queue. The broker knows when each worker is "Idle" or "Working", if a worker is idle, the broker will send it the next task on its queue. After a worker completes a task, it sends the broker a message telling it that it finished a task, and the broker will then send the next task on its queue, and if its queue is empty, then that worker's status will be set back to "Idle". You can inspect all these broker operations in `augur/routes/broker.py`.
2 : Yes different models should be developed depending on what is most fitting/compatible to the metric we are analyzing. Generally the 2 data types we are dealing with are time series and text. Time series has many different methods of detecting anomalies, we have an Isolation Forest method implemented for time series metrics in the insight worker. Numenta has done a good job analyzing and scoring different methods of time series anomaly detection, check some of them out here: https://github.com/numenta/NAB. Implementing a Numenta HTM, CAD OSE, or any other high scorer would be interesting. For text, we are interested in anomalous messages (which you and other gsoc applicants have done a great job exploring), and we have also been interested in sentiment analysis for a long time, but have not had the time to develop anything for gauging sentiment yet, this would be a great area to explore as well.
3 : When the insight worker discovers a new anomaly, it tells the Slack bot about it by sending it a JSON object over a HTTP post request with information about the anomaly. The Slack bot is still under active development. For further inquiries on how the Slack bot will work internally and if there is room for open contributions, please contact @jonahz5222 and @sgoggins.

**Comment by pratikmishra356** [comment]
@jonahz5222 @sgoggins could you please tell me about the mechanism of push notification and slack bot ,how user's data will be stored and used for generating insights according to the parameters given by the user.

**Comment by pratikmishra356** [comment]
@gabe-heim as per your suggestions I had searched about NAB, we can use this for selecting models which will perform better on wide variety of metrics.However Numenta HTM is incompatible as Nupic has not been upgraded to python3.
I also found https://github.com/yzhao062/pyod (pyod) quite useful for anomaly detection in multivariate data.

**Pull request merged**
