### PR TITLE
[DRAFT PR] Adding Packagist (PHP) support to the Libyear Worker 

### PR DESCRIPTION
**Pull request by Dhruv-Sachdev1313**
### DO NOT MERGE IT YET
This PR adds packagist support for the `deps_libyear_worker`. 

  
**Handled cases**. 
- The Composer file allows us to specify branches instead of versions of dependecy
- `<`,`>`,`>=` version reps
- `~` , `^` representation handled
- Wildcard version range
- hiphenated version range
- version range with `,` `||` and `  `
- cases where branch name are same as version rep.

### CODE REVIEW

**Comment by sgoggins** [comment]
@Dhruv-Sachdev1313: Is this ready?

**Comment by Dhruv-Sachdev1313** [comment]
@sgoggins The code is ready. I just have to test it once. If it breaks will add a fix and ping you for the review on slack! 🙂

**Comment by sgoggins** [comment]
@Dhruv-Sachdev1313 : Any chance this is complete3?

**Comment by Dhruv-Sachdev1313** [comment]
Hey @sgoggins: I got caught up with some stuff! Looking at this first thing this weekend! I will update you soon

**Pull request closed without merging**
