### PR TITLE
added notebook

### PR DESCRIPTION
**Pull request by ishagarg06**
Built the anomaly detection model using Isolation Forest. Worked on exploratory data analysis. And visualised the commits augur data set using KMeans clustering.
Please review it once. Thanks!
Regards- Isha Garg
Signed-off-by: ishagarg06 <ishagarg666@gmail.com>

### CODE REVIEW

**Comment by ishagarg06** [comment]
@sgoggins @germonprez @ccarterlandis kindly review..!

**Comment by sgoggins** [comment]
Its not the usual process to add something from master to dev, but I do see that this is a standalone notebook and Does not seem to affect anything else in the system, and is therefore worth exploring in dev.

**Comment by sgoggins** [comment]
@gabe-heim / @ccarterlandis : Do you agree?

**Comment by ccarterlandis** [comment]
The fact that it’s coming from @ishagarg06 ’s `master` branch doesn’t matter. It’s an independent notebook so yes, it doesn’t change anything, but I think this was a GSoC submission - you applied for GSoC with us, right @ishagarg06? If so, this should be merged into `GSoC`

**Comment by ishagarg06** [comment]
@ccarterlandis Basically this was an Outreachy submission and not the GSoC one.

**Comment by ccarterlandis** [comment]
Ah, got it, sorry about the mixup @ishagarg06. I know Outreachy submissions are long past due but it'd be nice to record this for posterity, so I'll go ahead and merge

**Pull request merged**
