### PR TITLE
Added my work on Gitlab data collector worker (GSoC MicroTasks)

### PR DESCRIPTION
**Pull request by abhinavbajpai2012**
Adding my work for Gitlab worker with the below features -
1. Fetches all the projects owned by the user.
2. Fetches Commits, Branches, Issues and Merge Requests with all the details and stores them as JSON in directories named after their parent project.

GSoC 202 Micro task-1

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@abhinavbajpai2012 Hi! If you could fix up the history, it would be easier to review. Thanks!

**Comment by abhinavbajpai2012** [comment]
@mrsaicharan1 yeah! will do it.

**Comment by mrsaicharan1** [comment]
@abhinavbajpai2012 Hi, you can reset the commit history by storing the changes as a stash and applying it to the same PR.

**Comment by mrsaicharan1** [comment]
https://git-scm.com/docs/git-stash

**Pull request closed without merging**
