### PR TITLE
Microtasks: Added Gitlab API script for augur

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Completed Microtasks 0, 1 & 2

- Whipped up Augur on a local setup, loaded sample data and understood how the data is extracted from various sources, pulled into augur's data models and the process in which insights are formed using SQL. 
- Gained an understanding as to how the workers are assigned tasks by the broker, how the housekeeper performs the data updation process and the overall workflow of augur

- Added GitLab API script to pull commits of a certain repository and saved it into a JSON file.

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
@sgoggins @ccarterlandis Hi, I have completed my microtasks. It would be great if you could review this. Thanks!

**Comment by mrsaicharan1** [comment]
@Nebrethar @sgoggins @ccarterlandis Hi, I've completed my microtasks. It's up for a review!

**Comment by ccarterlandis** [comment]
Hi @mrsaicharan1! The Travis build is failing because we use protected environment variables to configure our builds, and some of these configurations include sensitive credentials. For security, these credentials are only available to pull requests and pushes that come from within the main `chaoss/augur` repository. This is a limitation of Travis that I have yet to overcome, but I hope to have a workaround in the near future so that we can verify all PRs. For the time being, I can see that your code would not cause the tests to fail, so I will manually set the tests to pass for now. Thanks for understanding!

**Comment by ccarterlandis** [comment]
Hi @mrsaicharan1! The Travis build is failing because we use protected environment variables to configure our builds, and some of these configurations include sensitive credentials. For security, these credentials are only available to pull requests and pushes that come from within the main `chaoss/augur` repository. This is a limitation of Travis that I have yet to overcome, but I hope to have a workaround in the near future so that we can verify all PRs. For the time being, I can see that your code would not cause the tests to fail, so I will manually set the tests to pass for now. Thanks for understanding!

**Comment by mrsaicharan1** [comment]
@ccarterlandis Well that definitely does clear up the air. Thanks for the clarification. :D

**Pull request merged**
