### PR TITLE
Release 0.14 PR

### PR DESCRIPTION
**Pull request by sgoggins**
PR for Release.

### CODE REVIEW

**Review by ccarterlandis — COMMENTED** [review]
I need to finish getting some other things merged, update some docs, and write the CHANGELOG. Not quite ready yet.

**Comment by sgoggins** [comment]
@ccarterlandis : Its ready to merge when you say its ready.

**Comment by sgoggins** [comment]
@ccarterlandis : I think Travis-CI is failing because its looking for the max PR #, and that's the one I did from dev --> andrew earlier today. Its looking for 957, which is that one ... not sure why.

**Comment by sgoggins** [comment]
@ccarterlandis : closing this PR to test my theory.

**Pull request closed without merging**
