### PR TITLE
[api] Add endpoint to get repo by ID

### PR DESCRIPTION
**Pull request by Seltyk**
Documentation also written for this, though I'm not 100% sure "object" is a valid type. It definitely doesn't return an array.

**Description**
- Adds a utility endpoint to query a single repository. Contains much the same information as the /repos endpoint, but instead of returning an array of repositories, only one is returned. If the SQL read fails or no repository with the given ID is found, returns a 400.

I am told this functionality used to exist by using the special repo group ID 9999, and code using this feature [is still in Augur](https://github.com/chaoss/augur/blob/main/augur/tasks/data_analysis/insight_worker/tasks.py#L62), but that endpoint has been a 404 for as long as I have known Augur.

As usual, I also cleared linter warnings along the way (module-level import not at top of file and unused import) and removed ghostbytes.

**Notes for Reviewers**

The schema type is marked as `array` not because this endpoint actually returns an array -- it doesn't -- but because `object` wouldn't render the schema. For the first time, I had to document an error in the docs in the docs instead of fixing the error.

**Signed commits**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by Seltyk** [comment]
Further docs testing shows that if I set `type: array` the response schema looks fine but is described as an array. If I set `type: object` it doesn't show at all. The OpenAPI spec says that the schema object is a superset of JSON Schema, which defines both "array" and "object" as instance types. Interestingly, Augur's `spec.yml` doesn't appear to fit the OpenAPI documentation, but if that were the case, surely the docs wouldn't build correctly?

**Comment by Seltyk** [comment]
Another thought: this would make `/repos/:id` return more data per repo than `/repos`. This isn't dangerous, but it does mean inconsistency, which is not pleasant for frontends to parse. One of them ought to change.

**Comment by sgoggins** [comment]
@Seltyk : What kind of environment did you test this against? I'm trying to decide if I should merge into dev, or create a different branch and take it for a spin soon one way or another.

**Comment by Seltyk** [comment]
You might want to take it for a spin first, but the only *functional* change I made was adding an endpoint, so in theory it shouldn't have any issues going straight to dev

**Review by sgoggins — APPROVED** [review]
LGTM

**Pull request merged**
